---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.mac.com
  resources:
  - gatewayapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.mac.com
  resources:
  - gatewayapis/finalizers
  verbs:
  - update
- apiGroups:
  - platform.mac.com
  resources:
  - gatewayapis/status
  verbs:
  - get
  - patch
  - update
