# This rule is not used by the project runlocalk8smac itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.mac.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: runlocalk8smac
    app.kubernetes.io/managed-by: kustomize
  name: tenant-viewer-role
rules:
- apiGroups:
  - platform.mac.com
  resources:
  - tenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.mac.com
  resources:
  - tenants/status
  verbs:
  - get
