apiVersion: platform.mac.com/v1
kind: Tenant
metadata:
  name: payments-api
spec:
  teamName: payments
  apiName: payments-api
  environment: dev
  backend:
    url: https://payments.example.com
  authentication:
    type: oidc